 #define CLRBIT(WORD,BP) WORD&=~(1<<BP)
#define WRITEBYTE(WORD,STARTBIT,BYTE) \
        WORD=(WORD&(u32)~0xFF<<STARTBIT)|(BYTE<<STARTBIT)
#define READBIT(WORD,BIT) ((WORD>>BIT)&1)
#define WRITEBIT(WORD,BIT,BITLEVEL)\
        WORD=((WORD&~(1<<BIT))|(BITLEVEL<<BIT))
#define READWRITEBIT(WORD,DBIT,SBIT)\
        WORD=((WORD&~(1<<DBIT))|(((WORD>>SBIT)&1)<<DBIT))
#define READWRITEBIT2(DWORD,DBIT,SWORD,SBIT)\
        DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))
#define WRITENIBBLE(WORD,STARTBIT,NIBBLE) WORD=(WORD&(u32)~0x0F<<STARTBIT)|(NIBBLE<<STARTBIT)
#define READNIBBLE(WORD,STARTBIT) ((WORD>>STARTBIT)&0x0F)
